version: '3.8'

services:
  bazos-tracker:
    build: .
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      # Core application settings
      - PORT=${PORT:-5000}
      - HOST=0.0.0.0
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-false}
      
      # Application configuration
      - CHECK_INTERVAL=${CHECK_INTERVAL:-300}
      - FLASK_HTTPS=${FLASK_HTTPS:-false}
      
      # For Coolify compatibility
      - COOLIFY_URL=${COOLIFY_URL:-}
      - COOLIFY_BRANCH=${COOLIFY_BRANCH:-main}
      
    volumes:
      # Persist data between container restarts
      - bazos_data:/app/data
      - bazos_logs:/app/logs
      
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-5000}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

volumes:
  bazos_data:
    driver: local
  bazos_logs:
    driver: local

# Network configuration (optional)
networks:
  default:
    driver: bridge
